version: "3.8"
services:
  postgres:
    image: postgres:15.2
    container_name: "postgres-hwork-db"
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - postgres-hwork-volume:/var/lib/postgresql/data

volumes:
  postgres-hwork-volume:
    external: true